get latest birli build script

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -8,7 +8,6 @@ jobs:
   coverage:
     runs-on: ubuntu-latest
     container: mwatelescope/birli:latest
-    environment: CI
 
     steps:
       - name: Checkout sources
@@ -18,33 +17,27 @@ jobs:
 
       - name: Install nightly toolchain
         run: |
-          curl https://sh.rustup.rs -sSf | sh -s -- -y
-          export PATH="${HOME}/.cargo/bin:${PATH}"
           rustup set profile minimal
-          rustup toolchain install nightly --component llvm-tools-preview
-          rustup default nightly
+          rustup toolchain install nightly-2021-05-09 --component llvm-tools-preview
+          rustup default nightly-2021-05-09
 
       - name: Install Cargo Packages
         run: |
-          export PATH="${HOME}/.cargo/bin:${PATH}"
-          apt-get update
-          apt-get install -y unzip libssl-dev jq
-          cargo update
-          # TODO: thisn't
-          cargo update -p proc-macro2:1.0.29 --precise 1.0.28
-          cargo install --force cargo-make cargo-binutils --locked
+          cargo install --force cargo-make --locked --version '^0.32'
+          cargo install --force cargo-binutils --locked
         env:
           DEBIAN_FRONTEND: noninteractive
 
       - name: Generate test lcov coverage into coverage/ dir
         env:
-          LD_LIBRARY_PATH: /usr/local/lib/
           RUSTFLAGS: -Zinstrument-coverage
           LLVM_PROFILE_FILE: json5format-%m.profraw
         run: |
-          export PATH="${HOME}/.cargo/bin:${PATH}"
-          cargo make update
           mkdir -p coverage
+          # TODO: thisn't
+          cargo update -p proc-macro2 --precise 1.0.28 || echo "cargo update proc-macro2 failed"
+          cargo update -p approx:0.5.0 --precise 0.4.0 || echo "cargo update approx failed"
+          cargo update -p ndarray:0.15.3 --precise 0.14.0 || echo "cargo update ndarray failed"
           cargo test -- --include-ignored
           cargo profdata -- \
             merge -sparse json5format-*.profraw -o json5format.profdata
